"""Add completed column

Revision ID: 1fdfe7e0fcdd
Revises: 
Create Date: 2025-02-23 11:16:03.904341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fdfe7e0fcdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
